WorkHub/Models/Tasks.cs
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WorkHub.Models
{
    public class Tasks
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        public string TaskTitle { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        public string Reporter { get; set; } 

        [BsonRepresentation(BsonType.ObjectId)]
        public string ReporterID { get; set; }

        [DataType(DataType.Date)]
        public DateTime DueDate { get; set; }

        [DataType(DataType.Date)]
        public DateTime AssignDate { get; set; }
        public string Status { get; set; } 
        public List<string> Attachments { get; set; } 
        public double EstimationTime { get; set; } 

        [BsonRepresentation(BsonType.ObjectId)]
        public string ProjectID { get; set; } 
        public List<string> Assignee { get; set; }

    }
}

WorkHub/Controllers/Developer/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorkHub.Controllers.Developer
{
    public class TaskController : Controller
    {
        // GET: Task
        public ActionResult Index()
        {
            return View();
        }
    }
}


/*using MongoDB.Bson;
using MongoDB.Driver;
using System.Threading.Tasks;
using System.Web.Mvc;
using WorkHub.Models;
using WorkHub.Services;

namespace WorkHub.Controllers
{
    public class TasksController : Controller
    {
        private IMongoCollection<Task> _taskCollection;

        public TasksController()
        {
            _taskCollection = MongoDBHelper.GetCollection<Task>("Tasks");
        }

        // GET: Tasks
        public ActionResult Index(string search = null, string filterStatus = null)
        {
            var filter = Builders<Task>.Filter.Empty;

            if (!string.IsNullOrEmpty(search))
            {
                filter &= Builders<Task>.Filter.Regex("TaskName", new BsonRegularExpression(search, "i"));
            }

            if (!string.IsNullOrEmpty(filterStatus))
            {
                filter &= Builders<Task>.Filter.Eq("Status", filterStatus);
            }

            var tasks = _taskCollection.Find(filter).ToList();
            return View(tasks);
        }

        // GET: Tasks/Details/5
        public ActionResult Details(string id)
        {
            if (!ObjectId.TryParse(id, out var objectId))
            {
                return HttpNotFound();
            }

            var task = _taskCollection.Find(t => t.Id == objectId).FirstOrDefault();
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // GET: Tasks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tasks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Task task)
        {
            if (ModelState.IsValid)
            {
                _taskCollection.InsertOne(task);
                return RedirectToAction("Index");
            }
            return View(task);
        }

        // GET: Tasks/Edit/5
        public ActionResult Edit(string id)
        {
            if (!ObjectId.TryParse(id, out var objectId))
            {
                return HttpNotFound();
            }

            var task = _taskCollection.Find(t => t.Id == objectId).FirstOrDefault();
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: Tasks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, Task taskIn)
        {
            if (!ObjectId.TryParse(id, out var objectId))
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                var filter = Builders<Task>.Filter.Eq(t => t.Id, objectId);
                _taskCollection.ReplaceOne(filter, taskIn);
                return RedirectToAction("Index");
            }
            return View(taskIn);
        }

        // GET: Tasks/Delete/5
        public ActionResult Delete(string id)
        {
            if (!ObjectId.TryParse(id, out var objectId))
            {
                return HttpNotFound();
            }

            var task = _taskCollection.Find(t => t.Id == objectId).FirstOrDefault();
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            if (!ObjectId.TryParse(id, out var objectId))
            {
                return HttpNotFound();
            }

            var filter = Builders<Task>.Filter.Eq(t => t.Id, objectId);
            _taskCollection.DeleteOne(filter);
            return RedirectToAction("Index");
        }
    }
}

*/

WorkHub/Controllers/Manager/ManagerController.cs
using MongoDB.Bson;
using MongoDB.Driver;
using MongoDB.Driver.GridFS;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using WorkHub.Models;
using WorkHub.Services;
using Newtonsoft.Json;

namespace WorkHub.Controllers
{
    public class ManagerController : Controller
    {
        private readonly IMongoCollection<UserSignUp> _userCollection;
        private readonly IMongoCollection<CreateaProject> _projectCollection;
        private readonly IMongoCollection<TaskCompletionRequest> _taskCompletionRequestCollection;
        public readonly IMongoCollection<Tasks> _tasksCollection;
        public readonly IMongoCollection<UserProfile> _userProfilesCollection;
        public readonly IMongoCollection<Comment> _commentCollection;
        public readonly IMongoCollection<Notification> _userNotificationsCollection;

        public ManagerController()
        {
            _userCollection = MongoDBHelper.GetCollection<UserSignUp>("Users");
            _projectCollection = MongoDBHelper.GetCollection<CreateaProject>("Project");
            _taskCompletionRequestCollection = MongoDBHelper.GetCollection<TaskCompletionRequest>("TaskCompletionRequest");
            _tasksCollection = MongoDBHelper.GetCollection<Tasks>("Tasks");
            _userProfilesCollection = MongoDBHelper.GetCollection<UserProfile>("UserProfiles");
            _commentCollection = MongoDBHelper.GetCollection<Comment>("Comment");
            _userNotificationsCollection = MongoDBHelper.GetCollection<Notification>("Notifications");
        }

        // GET: Manager
        public ActionResult ManagerIndex()
        {
            return View();
        }

        // GET: Manager/CreateProject (This is for displaying the form)
        public ActionResult CreateProject(string id, string title, string desc, string sdate, string edate, int act)
        {
            try
            {
                if (act == 1)
                {

                    var users = _userCollection.Find(_ => true).ToList();


                    ViewBag.Users = users;
                    ViewBag.act = 1;


                    return View(new CreateaProject());
                }
                else if (act == 2)
                {
                    var users = _userCollection.Find(_ => true).ToList();


                    ViewBag.act = 2;
                    ViewBag.Users = users;
                    CreateaProject model = new CreateaProject { ProjectName = title, Id = id, Description = desc, StartDate = DateTime.Parse(sdate), EndDate = DateTime.Parse(edate) };


                    return View(model);
                }
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "An error occurred while fetching users.");



                return View(new CreateaProject());
            }

            return View(new CreateaProject());
        }


        [HttpPost]
        public ActionResult CreateProject(CreateaProject model, int func)
        {
            try
            {
                if (func == 1)
                {
                    if (model.Status == null)
                    {
                        model.Status = "Ongoing";
                    }

                    model.StartDate = model.StartDate.AddDays(1);
                    model.EndDate = model.EndDate.AddDays(1);

                    _projectCollection.InsertOne(model);


                    return RedirectToAction("ManagerDashboard");
                }
                else if (func == 2)
                {

                    var existingProject = _projectCollection.Find(p => p.Id == model.Id).FirstOrDefault();
                    if (existingProject == null)
                    {
                        ModelState.AddModelError("", "Project not found.");
                    }
                    else
                    {

                        existingProject.ProjectName = model.ProjectName;
                        existingProject.Description = model.Description;
                        existingProject.StartDate = model.StartDate.AddDays(1);
                        existingProject.EndDate = model.EndDate.AddDays(1);
                        if (model.Status != null)
                        {
                            existingProject.Status = model.Status;
                        }
                        existingProject.TeamMembers = model.TeamMembers;


                        _projectCollection.ReplaceOne(p => p.Id == existingProject.Id, existingProject);

                        return RedirectToAction("ManagerDashboard");
                    }
                }


            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "An error occurred while saving the project.");

            }


            var users = _userCollection.Find(_ => true).ToList();
            ViewBag.Users = users;
            return View(model);
        }

        public ActionResult uploadProjectFiles(string id, HttpPostedFileBase[] attachments)
        {
            var existingProject = _projectCollection.Find(t => t.Id == id).FirstOrDefault();
            if (attachments != null && attachments.Length > 0)
            {
                UploadFiles(existingProject, attachments);
            }
            else
            {
                return RedirectToAction("ManagerDashboard");
            }

            return RedirectToAction("ProjectDetails", new { id = id });

        }

        private void UploadFiles(CreateaProject model, HttpPostedFileBase[] attachments)
        {
            var database = MongoDBHelper.GetDatabase();
            var bucket = new GridFSBucket(database);

            /*model.Attachments = new List<string>();*/

            foreach (var file in attachments)
            {
                if (file != null && file.ContentLength > 0)
                {

                    var fileId = ObjectId.GenerateNewId();
                    var fileName = $"{fileId}{Path.GetExtension(file.FileName)}";

                    using (var stream = file.InputStream)
                    {

                        bucket.UploadFromStream(fileName, stream);
                    }


                    var projectFile = new Models.File
                    {
                        Id = fileId,
                        TaskID = model.Id.ToString(),
                        FileName = file.FileName,
                        FilePath = fileName,
                        ContentType = file.ContentType,
                        Size = file.ContentLength,
                        UploadedDate = DateTime.Now
                    };


                    var projectFilesCollection = MongoDBHelper.GetCollection<Models.File>("ProjectFiles");
                    projectFilesCollection.InsertOne(projectFile);


                    /*model.Attachments.Add(fileId.ToString());*/
                }
            }
        }

        public ActionResult DownloadFiles(string fileId)
        {
            try
            {

                var objectId = new ObjectId(fileId);


                var projectFilesCollection = MongoDBHelper.GetCollection<Models.File>("ProjectFiles");
                var projectFile = projectFilesCollection.Find(f => f.Id == objectId).FirstOrDefault();

                if (projectFile == null)
                {
                    return HttpNotFound("File not found.");
                }


                var database = MongoDBHelper.GetDatabase();
                var bucket = new GridFSBucket(database);


                byte[] fileBytes;
                using (var stream = new MemoryStream())
                {
                    bucket.DownloadToStreamByName(projectFile.FilePath, stream);
                    fileBytes = stream.ToArray();
                }


                return File(fileBytes, projectFile.ContentType, projectFile.FileName);
            }
            catch (Exception ex)
            {

                ViewBag.Error = "Error downloading file: " + ex.Message;
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult DeleteFiles(string projectid, string[] fileIds)
        {
            if (fileIds != null && fileIds.Length > 0)
            {
                var database = MongoDBHelper.GetDatabase();

                var projectFilesCollection = MongoDBHelper.GetCollection<Models.File>("ProjectFiles");
                var projectFilesToDelete = projectFilesCollection.Find(f => fileIds.Contains(f.Id.ToString())).ToList();

                foreach (var projectFile in projectFilesToDelete)
                {
                    var filePath = projectFile.FilePath;

                    var filesCollection = database.GetCollection<BsonDocument>("fs.files");
                    var fileDocument = filesCollection.Find(Builders<BsonDocument>.Filter.Eq("filename", filePath)).FirstOrDefault();

                    if (fileDocument != null)
                    {
                        var fileId = fileDocument["_id"].AsObjectId;

                        var chunksCollection = database.GetCollection<BsonDocument>("fs.chunks");
                        chunksCollection.DeleteMany(Builders<BsonDocument>.Filter.Eq("files_id", fileId));

                        filesCollection.DeleteMany(Builders<BsonDocument>.Filter.Eq("_id", fileId));
                    }
                }

                var filter = Builders<Models.File>.Filter.In(f => f.Id, projectFilesToDelete.Select(tf => tf.Id));
                projectFilesCollection.DeleteMany(filter);
            }

            return RedirectToAction("ProjectDetails", new { id = projectid });
        }

        public ActionResult ViewProjects()
        {
            try
            {

WorkHub/Views/Task/AddTask.cshtml
@model WorkHub.Models.Tasks

@{
    ViewBag.Title = "Add Task";
    Layout = "~/Views/Manager/ManagerIndex.cshtml";
}

@if (ViewBag.act == 1)
{
    <h2>Add Task</h2>
    <p>Fill in the details below to add a new task.</p>
}
else if (ViewBag.act == 2)
{
    <h2>Edit Task</h2>
    <p>Fill in the details below to edit the task.</p>
}


@using (Html.BeginForm("Create", "Task", new { func = ViewBag.act }, FormMethod.Post, new { @class = "needs-validation", novalidate = "novalidate", enctype = "multipart/form-data" }))
{

    if (ViewBag.act == 2)
    {
        @Html.HiddenFor(m => m.Id)
    }

    <div class="card">
        <div class="card-header">
            <h5 class="card-title">Task Details</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-8">
                    <!-- Task Title -->
                    <div class="mb-3">
                        @Html.LabelFor(m => m.TaskTitle, new { @class = "form-label" })
                        @Html.TextBoxFor(m => m.TaskTitle, new { @class = "form-control", placeholder = "Enter task title", required = "required" })
                    </div>

                    <!-- Description -->
                    <div class="mb-3">
                        @Html.LabelFor(m => m.Description, new { @class = "form-label" })
                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control", placeholder = "Enter task description", rows = "4", required = "required" })
                    </div>

                    <!-- Reporter -->
                    <div class="mb-3">
                        @Html.Label("Reporter", new { @class = "form-label" })
                        @if (ViewBag.act == 1)
                        {
                            @Html.TextBox("Reporter", ViewBag.Name as string, new { @class = "form-control", @readonly = "readonly" })
                            @Html.Hidden("ReporterID", ViewBag.ID as string)
                        }
                        else if (ViewBag.act == 2)
                        {
                            @Html.TextBox("Reporter", Model.Reporter as string, new { @class = "form-control", @readonly = "readonly" })
                            @Html.Hidden("ReporterID", Model.ReporterID as string)
                        }
                    </div>

                    <!-- Due Date -->
                    <div class="mb-3">
                        @Html.Label("DueDate", "Due Date", new { @class = "form-label" })
                        @*@Html.TextBoxFor(m => m.DueDate, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date", required = "required" })*@
                        @if (ViewBag.act == 1)
                        {
                            @Html.TextBoxFor(m => m.DueDate, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date", required = "required", Value = DateTime.Now.ToString("yyyy-MM-dd") })
                        }
                        else if (ViewBag.act == 2)
                        {
                            @Html.TextBoxFor(m => m.DueDate, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date", required = "required", Value = Model.DueDate.ToString("yyyy-MM-dd") })
                        }
                    </div>

                    <!-- Status -->
                    <div class="mb-3">
                        @Html.LabelFor(m => m.Status, new { @class = "form-label" })
                        @Html.DropDownListFor(m => m.Status, new SelectList(new List<string> { "To Do", "In Progress", "Done" }), new { @class = "form-control", required = "required" })
                    </div>

                    <!-- Estimation Time -->
                    <div class="mb-3">
                        @Html.Label("EstimationTime", "Estimation Time", new { @class = "form-label" })
                        @if (ViewBag.act == 1)
                        {
                            @Html.TextBoxFor(m => m.EstimationTime, new { @class = "form-control", type = "number", step = "1", placeHolder = "Estemation Time", required = "required" })
                        }
                        else if (ViewBag.act == 2)
                        {
                            @Html.TextBoxFor(m => m.EstimationTime, new { @class = "form-control", type = "number", step = "1", value = Model.EstimationTime, required = "required" })
                        }
                    </div>

                    <!-- Project -->
                    <div class="mb-3">
                        @Html.Label("ProjectID", "Project Name", new { @class = "form-label" })
                        @Html.DropDownListFor(m => m.ProjectID, new SelectList(ViewBag.Projects, "Id", "ProjectName"), new { @class = "form-control", required = "required" })
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-label">Attachments:</div>
                    <div class="drag-drop-area" id="drop-area">
                        <div class="dz-message needsclick">
                            <i class="h3 text-muted ri-upload-cloud-2-line"></i>
                            <h4>Drop files here or click to upload.</h4>
                        </div>
                        <input type="file" id="fileElem" name="attachments" multiple class="form-control file-input"
                               accept=".jpg, .jpeg, .png, .gif, .pdf, .doc, .docx, .xls, .xlsx, .ppt, .pptx, .zip, .rar" />
                        <i class="bx bx-cloud-upload" style="font-size:2rem;"></i>
                        <ul id="fileList" class="list-group"></ul>
                    </div>


                    @*<div class="form-label mt-4">Add users:</div>*@

                    <div class="mb-3">
                        @Html.LabelFor(m => m.Assignee, new { @class = "form-label" })

                        <div class="card p-3">
                            @foreach (var user in (IEnumerable<WorkHub.Models.UserSignUp>)ViewBag.Users)
                            {
                                <div class="form-check mb-2">
                                    <input type="checkbox"
                                           class="form-check-input"
                                           id="user_@user.Id"
                                           name="Assignee"
                                           value="@user.Id"
                                           @if (ViewBag.act == 2 && Model.Assignee != null) { @(Model.Assignee.Contains(user.Id) ? "checked" : "") } />

                                    <label class="form-check-label" for="user_@user.Id">
                                        @user.Username
                                    </label>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-save"></i> Save Task
            </button>
            <a href="@Url.Action("ManagerIndex", "Manager")" class="btn btn-secondary">
                <i class="fas fa-arrow-left"></i> Back to Dashboard
            </a>
        </div>
    </div>
}

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const fileInput = document.getElementById('fileElem');
        const fileList = document.getElementById('fileList');

        fileInput.addEventListener('change', function () {
            fileList.innerHTML = ""; 
            const files = fileInput.files;

            if (files.length > 0) {
                fileList.style.display = 'block'; 
                for (let i = 0; i < files.length; i++) {
                    const li = document.createElement('li');
                    li.textContent = files[i].name;
                    li.classList.add('list-group-item');
                    fileList.appendChild(li);
                }
            } else {
                fileList.style.display = 'none'; 
            }
        });
    });
</script>

<style>
    .drag-drop-area {
        border: 2px dashed #007bff;
        border-radius: 10px;
        padding: 20px;
        text-align: center;
        position: relative;
        margin-bottom: 20px;
    }

    .file-input {
        opacity: 0;
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        cursor: pointer;
    }

    .list-group {
        max-height: 200px;
        overflow-y: auto;
        display: none;
    }

    .selected {
        background-color: #e9ecef;
    }

    .form-check-label {
        font-weight: bold;
        color: #333;
    }

    .card {
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .form-check-input {
        width: 1.5em;
        height: 1.5em;
    }

    .drag-drop-area {
        border: 2px dashed #007bff;
        border-radius: 10px;
        padding: 20px;
        text-align: center;
        position: relative;
        margin-bottom: 20px;
    }

    .file-input {
        opacity: 0;
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        cursor: pointer;
    }

    #fileList {
        margin-top: 10px;
        padding-left: 0;
    }

        #fileList li {
            background-color: #f8f9fa;
            border: 1px solid #dee2e6;
            border-radius: 5px;
            margin-bottom: 5px;
            padding: 5px 10px;
            list-style: none;
        }

    #fileList {
        display: none;
        max-height: 200px;
        overflow-y: auto;
    }
</style>