WorkHub/Models/Notification.cs
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WorkHub.Models
{
    public class Notification
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        public string UserId { get; set; } 

        public string Message { get; set; } 

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow; 

        public bool IsRead { get; set; } = false; 
    }
}

WorkHub/Models/UserProfile.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;

namespace WorkHub.Models
{
    public class UserProfile
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        public string Username { get; set; }

        public string Status { get; set; }

        public string Country { get; set; }

        public List<string> Languages { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }

        public string City { get; set; }

        public string Designation { get; set; }

        public string ProfilePicture { get; set; }

        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        [BsonDateTimeOptions(Kind = DateTimeKind.Local)]
        public DateTime UpdatedAt { get; set; } = DateTime.Now;

        public string Role { get; set; } // Admin, Manager, Developer.

        public string Facebook { get; set; }

        public string Twitter { get; set; }

        public string LinkedIn { get; set; }

        public string GitHub { get; set; }
    }
}

WorkHub/Models/ViewTasks.cs
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WorkHub.Models
{
    public class ViewTasks
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public ObjectId Id { get; set; }

        public string TaskName { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Assignee { get; set; }
        public DateTime DueDate { get; set; }
    }
}

WorkHub/Controllers/Developer/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorkHub.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult DashboardIndex()
        {
            return View();
        }
    }
}

WorkHub/Controllers/Developer/DeveloperController.cs
using MongoDB.Bson;
using MongoDB.Driver;
using MongoDB.Driver.GridFS;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using WorkHub.Models;
using WorkHub.Services;
using Newtonsoft.Json;

namespace WorkHub.Controllers
{
    public class DeveloperController : Controller
    {
        private readonly IMongoCollection<UserSignUp> _userCollection;
        private readonly IMongoCollection<CreateaProject> _projectCollection;
        private readonly IMongoCollection<TaskCompletionRequest> _taskCompletionRequestCollection;
        public readonly IMongoCollection<Tasks> _tasksCollection;
        public readonly IMongoCollection<UserProfile> _userProfilesCollection;
        public readonly IMongoCollection<Comment> _commentCollection;
        public readonly IMongoCollection<Notification> _userNotificationsCollection;

        public DeveloperController()
        {
            _userCollection = MongoDBHelper.GetCollection<UserSignUp>("Users");
            _projectCollection = MongoDBHelper.GetCollection<CreateaProject>("Project");
            _taskCompletionRequestCollection = MongoDBHelper.GetCollection<TaskCompletionRequest>("TaskCompletionRequest");
            _tasksCollection = MongoDBHelper.GetCollection<Tasks>("Tasks");
            _userProfilesCollection = MongoDBHelper.GetCollection<UserProfile>("UserProfiles");
            _commentCollection = MongoDBHelper.GetCollection<Comment>("Comment");
            _userNotificationsCollection = MongoDBHelper.GetCollection<Notification>("Notifications");
        }

        // GET: Manager
        public ActionResult DeveloperIndex()
        {
            return View();
        }

        // GET: Manager/CreateProject (This is for displaying the form)
        public ActionResult CreateProject(string id, string title, string desc, string sdate, string edate, int act)
        {
            try
            {
                if (act == 1)
                {

                    var users = _userCollection.Find(_ => true).ToList();


                    ViewBag.Users = users;
                    ViewBag.act = 1;


                    return View(new CreateaProject());
                }
                else if (act == 2)
                {
                    var users = _userCollection.Find(_ => true).ToList();


                    ViewBag.act = 2;
                    ViewBag.Users = users;
                    CreateaProject model = new CreateaProject { ProjectName = title, Id = id, Description = desc, StartDate = DateTime.Parse(sdate), EndDate = DateTime.Parse(edate) };


                    return View(model);
                }
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "An error occurred while fetching users.");



                return View(new CreateaProject());
            }

            return View(new CreateaProject());
        }


        [HttpPost]
        public ActionResult CreateProject(CreateaProject model, int func)
        {
            try
            {
                if (func == 1)
                {
                    if (model.Status == null)
                    {
                        model.Status = "Ongoing";
                    }

                    model.StartDate = model.StartDate.AddDays(1);
                    model.EndDate = model.EndDate.AddDays(1);

                    _projectCollection.InsertOne(model);


                    return RedirectToAction("ManagerDashboard");
                }
                else if (func == 2)
                {

                    var existingProject = _projectCollection.Find(p => p.Id == model.Id).FirstOrDefault();
                    if (existingProject == null)
                    {
                        ModelState.AddModelError("", "Project not found.");
                    }
                    else
                    {

                        existingProject.ProjectName = model.ProjectName;
                        existingProject.Description = model.Description;
                        existingProject.StartDate = model.StartDate.AddDays(1);
                        existingProject.EndDate = model.EndDate.AddDays(1);
                        if (model.Status != null)
                        {
                            existingProject.Status = model.Status;
                        }
                        existingProject.TeamMembers = model.TeamMembers;


                        _projectCollection.ReplaceOne(p => p.Id == existingProject.Id, existingProject);

                        return RedirectToAction("ManagerDashboard");
                    }
                }


            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "An error occurred while saving the project.");

            }


            var users = _userCollection.Find(_ => true).ToList();
            ViewBag.Users = users;
            return View(model);
        }

        public ActionResult uploadProjectFiles(string id, HttpPostedFileBase[] attachments)
        {
            var existingProject = _projectCollection.Find(t => t.Id == id).FirstOrDefault();
            if (attachments != null && attachments.Length > 0)
            {
                UploadFiles(existingProject, attachments);
            }
            else
            {
                return RedirectToAction("ManagerDashboard");
            }

            return RedirectToAction("ProjectDetails", new { id = id });

        }

        private void UploadFiles(CreateaProject model, HttpPostedFileBase[] attachments)
        {
            var database = MongoDBHelper.GetDatabase();
            var bucket = new GridFSBucket(database);

            /*model.Attachments = new List<string>();*/

            foreach (var file in attachments)
            {
                if (file != null && file.ContentLength > 0)
                {

                    var fileId = ObjectId.GenerateNewId();
                    var fileName = $"{fileId}{Path.GetExtension(file.FileName)}";

                    using (var stream = file.InputStream)
                    {

                        bucket.UploadFromStream(fileName, stream);
                    }


                    var projectFile = new Models.File
                    {
                        Id = fileId,
                        TaskID = model.Id.ToString(),
                        FileName = file.FileName,
                        FilePath = fileName,
                        ContentType = file.ContentType,
                        Size = file.ContentLength,
                        UploadedDate = DateTime.Now
                    };


                    var projectFilesCollection = MongoDBHelper.GetCollection<Models.File>("ProjectFiles");
                    projectFilesCollection.InsertOne(projectFile);


                    /*model.Attachments.Add(fileId.ToString());*/
                }
            }
        }

        public ActionResult DownloadFiles(string fileId)
        {
            try
            {

                var objectId = new ObjectId(fileId);


                var projectFilesCollection = MongoDBHelper.GetCollection<Models.File>("ProjectFiles");
                var projectFile = projectFilesCollection.Find(f => f.Id == objectId).FirstOrDefault();

                if (projectFile == null)
                {
                    return HttpNotFound("File not found.");
                }


                var database = MongoDBHelper.GetDatabase();
                var bucket = new GridFSBucket(database);


                byte[] fileBytes;
                using (var stream = new MemoryStream())
                {
                    bucket.DownloadToStreamByName(projectFile.FilePath, stream);
                    fileBytes = stream.ToArray();
                }


                return File(fileBytes, projectFile.ContentType, projectFile.FileName);
            }
            catch (Exception ex)
            {

                ViewBag.Error = "Error downloading file: " + ex.Message;
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult DeleteFiles(string projectid, string[] fileIds)
        {
            if (fileIds != null && fileIds.Length > 0)
            {

                var database = MongoDBHelper.GetDatabase();


                var projectFilesCollection = MongoDBHelper.GetCollection<Models.File>("ProjectFiles");
                var projectFilesToDelete = projectFilesCollection.Find(f => fileIds.Contains(f.Id.ToString())).ToList();

                foreach (var projectFile in projectFilesToDelete)
                {

                    var filePath = projectFile.FilePath;


                    var filesCollection = database.GetCollection<BsonDocument>("fs.files");
                    var fileDocument = filesCollection.Find(Builders<BsonDocument>.Filter.Eq("filename", filePath)).FirstOrDefault();

                    if (fileDocument != null)
                    {
                        var fileId = fileDocument["_id"].AsObjectId;


                        var chunksCollection = database.GetCollection<BsonDocument>("fs.chunks");
                        chunksCollection.DeleteMany(Builders<BsonDocument>.Filter.Eq("files_id", fileId));


                        filesCollection.DeleteMany(Builders<BsonDocument>.Filter.Eq("_id", fileId));
                    }
                }


                var filter = Builders<Models.File>.Filter.In(f => f.Id, projectFilesToDelete.Select(tf => tf.Id));
                projectFilesCollection.DeleteMany(filter);
            }

            return RedirectToAction("ProjectDetails", new { id = projectid });
        }

        public ActionResult ViewProjects()
        {
            try
            {

WorkHub/Controllers/Developer/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorkHub.Controllers.Developer
{
    public class TaskController : Controller
    {
        // GET: Task
        public ActionResult Index()
        {
            return View();
        }
    }
}


/*using MongoDB.Bson;
using MongoDB.Driver;
using System.Threading.Tasks;
using System.Web.Mvc;
using WorkHub.Models;
using WorkHub.Services;

namespace WorkHub.Controllers
{
    public class TasksController : Controller
    {
        private IMongoCollection<Task> _taskCollection;

        public TasksController()
        {
            _taskCollection = MongoDBHelper.GetCollection<Task>("Tasks");
        }

        // GET: Tasks
        public ActionResult Index(string search = null, string filterStatus = null)
        {
            var filter = Builders<Task>.Filter.Empty;

            if (!string.IsNullOrEmpty(search))
            {
                filter &= Builders<Task>.Filter.Regex("TaskName", new BsonRegularExpression(search, "i"));
            }

            if (!string.IsNullOrEmpty(filterStatus))
            {
                filter &= Builders<Task>.Filter.Eq("Status", filterStatus);
            }

            var tasks = _taskCollection.Find(filter).ToList();
            return View(tasks);
        }

        // GET: Tasks/Details/5
        public ActionResult Details(string id)
        {
            if (!ObjectId.TryParse(id, out var objectId))
            {
                return HttpNotFound();
            }

            var task = _taskCollection.Find(t => t.Id == objectId).FirstOrDefault();
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // GET: Tasks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tasks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Task task)
        {
            if (ModelState.IsValid)
            {
                _taskCollection.InsertOne(task);
                return RedirectToAction("Index");
            }
            return View(task);
        }

        // GET: Tasks/Edit/5
        public ActionResult Edit(string id)
        {
            if (!ObjectId.TryParse(id, out var objectId))
            {
                return HttpNotFound();
            }

            var task = _taskCollection.Find(t => t.Id == objectId).FirstOrDefault();
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: Tasks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, Task taskIn)
        {
            if (!ObjectId.TryParse(id, out var objectId))
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                var filter = Builders<Task>.Filter.Eq(t => t.Id, objectId);
                _taskCollection.ReplaceOne(filter, taskIn);
                return RedirectToAction("Index");
            }
            return View(taskIn);
        }

        // GET: Tasks/Delete/5
        public ActionResult Delete(string id)
        {
            if (!ObjectId.TryParse(id, out var objectId))
            {
                return HttpNotFound();
            }

            var task = _taskCollection.Find(t => t.Id == objectId).FirstOrDefault();
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            if (!ObjectId.TryParse(id, out var objectId))
            {
                return HttpNotFound();
            }

            var filter = Builders<Task>.Filter.Eq(t => t.Id, objectId);
            _taskCollection.DeleteOne(filter);
            return RedirectToAction("Index");
        }
    }
}

*/

WorkHub/Views/Developer/ActiveBran.cshtml
@{
    ViewBag.Title = "ActiveBran";
    Layout = "~/Views/Developer/DeveloperIndex.cshtml";
}

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <h1 class="text-center mb-4">Active Branches</h1>

            <!-- Branch cards -->
            <div class="branch-card">
                <h3>Branch Name 1</h3>
                <p><strong>Last Commit:</strong> Commit message or details</p>
                <p><strong>Updated:</strong> Date and Time</p>
                <span class="badge badge-success">Active</span>
                <a href="#" class="btn btn-sm btn-outline-primary"><i class="fas fa-eye"></i> View Branch</a>
            </div>

            <div class="branch-card">
                <h3>Branch Name 2</h3>
                <p><strong>Last Commit:</strong> Commit message or details</p>
                <p><strong>Updated:</strong> Date and Time</p>
                <span class="badge badge-warning">Pending</span>
                <a href="#" class="btn btn-sm btn-outline-primary"><i class="fas fa-eye"></i> View Branch</a>
            </div>

            <div class="branch-card">
                <h3>Branch Name 3</h3>
                <p><strong>Last Commit:</strong> Commit message or details</p>
                <p><strong>Updated:</strong> Date and Time</p>
                <span class="badge badge-danger">Inactive</span>
                <a href="#" class="btn btn-sm btn-outline-primary"><i class="fas fa-eye"></i> View Branch</a>
            </div>

            <!-- Add more branch cards as needed -->

        </div>
    </div>
</div>

WorkHub/Views/Developer/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Developer/DeveloperIndex.cshtml";

}


                        <h1 class="mb-4 text-center">Developer Dashboard Overview</h1>

                        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
                            <!-- Project Overview Card -->
                            <div class="col">
                                <div class="card h-100 text-center">
                                    <div class="card-body">
                                        <i class="fas fa-project-diagram fa-3x mb-3"></i>
                                        <h5 class="card-title">Project Overview</h5>
                                        <p class="card-text">View project details, recent commits, and active branches.</p>
                                        @*@<a href="#" class="btn btn-primary">View Details</a>*@
                                        <a href="@Url.Action("ProjectDetails", "Developer")" class="btn btn-primary">
                                            View Details
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <!-- Code Repository Card -->
                            <div class="col">
                                <div class="card h-100 text-center">
                                    <div class="card-body">
                                        <i class="fas fa-code-branch fa-3x mb-3"></i>
                                        <h5 class="card-title">Code Repository</h5>
                                        <p class="card-text">Access the code repository, view commit history, and manage branches.</p>
                                        @*<a href="#" class="btn btn-primary">View Repository</a>*@
                                        <a href="@Url.Action("RepositoryView", "Developer")" class="btn btn-primary">
                                            View Repository
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <!-- Build Management Card -->
                            <div class="col">
                                <div class="card h-100 text-center">
                                    <div class="card-body">
                                        <i class="fas fa-cogs fa-3x mb-3"></i>
                                        <h5 class="card-title">Build Management</h5>
                                        <p class="card-text">Check build status, view build history, and trigger new builds.</p>

                                        <a href="@Url.Action("NewBuild", "Developer")" class="btn btn-primary">
                                            Manage Builds
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <!-- Deployment Card -->
                            <div class="col">
                                <div class="card h-100 text-center">
                                    <div class="card-body">
                                        <i class="fas fa-cloud-upload-alt fa-3x mb-3"></i>
                                        <h5 class="card-title">Deployment</h5>
                                        <p class="card-text">View deployment status, deployment history, and trigger new deployments.</p>

                                        <a href="@Url.Action("NewDep", "Developer")" class="btn btn-primary">
                                            Manage Deployments
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <!-- Task Management Card -->
                            <div class="col">
                                <div class="card h-100 text-center">
                                    <div class="card-body">
                                        <i class="fas fa-tasks fa-3x mb-3"></i>
                                        <h5 class="card-title">Task Management</h5>
                                        <p class="card-text">View tasks, create new tasks, and assign tasks to team members.</p>

                                        <a href="@Url.Action("ViewTasks", "Developer")" class="btn btn-primary">
                                            Manage Tasks
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <!-- Logs and Monitoring Card -->
                            <div class="col">
                                <div class="card h-100 text-center">
                                    <div class="card-body">
                                        <i class="fas fa-file-alt fa-3x mb-3"></i>
                                        <h5 class="card-title">Logs and Monitoring</h5>
                                        <p class="card-text">View application and system logs, and monitor performance metrics.</p>
                                        <a href="#" class="btn btn-primary">View Logs</a>
                                    </div>
                                </div>
                            </div>

                            <!-- API Management Card -->
                            <div class="col">
                                <div class="card h-100 text-center">
                                    <div class="card-body">
                                        <i class="fas fa-plug fa-3x mb-3"></i>
                                        <h5 class="card-title">API Management</h5>
                                        <p class="card-text">Manage APIs, view documentation, and test APIs.</p>
                                        <a href="#" class="btn btn-primary">Manage APIs</a>
                                    </div>
                                </div>
                            </div>

                            <!-- User Management Card -->
                            <div class="col">
                                <div class="card h-100 text-center">
                                    <div class="card-body">
                                        <i class="fas fa-user-shield fa-3x mb-3"></i>
                                        <h5 class="card-title">User Management</h5>
                                        <p class="card-text">Manage user access, roles, and permissions.</p>
                                        <a href="#" class="btn btn-primary">Manage Users</a>
                                    </div>
                                </div>
                            </div>



                            <!-- Reports Card -->
                            <div class="col">
                                <div class="card h-100 text-center">
                                    <div class="card-body">
                                        <i class="fas fa-chart-bar fa-3x mb-3"></i>
                                        <h5 class="card-title">Reports</h5>
                                        <p class="card-text">View build, deployment, and task reports.</p>

                                        <a href="@Url.Action("ProjectProgress", "Developer")" class="btn btn-primary">
                                            View Reports
                                        </a>
                                    </div>
                                </div>
                            </div>

                        </div>


                        <!-- /Content -->
                        <!-- Footer -->
                        @*<footer class="content-footer footer bg-footer-theme">
                                <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                                    <div class="mb-2 mb-md-0">
                                        ©
                                        <script>document.write(new Date().getFullYear());</script>, made with ❤️ by <a href="https://themeselection.com" target="_blank" class="footer-link fw-bolder">ThemeSelection</a>
                                    </div>
                                    <div>
                                        <a href="https://themeselection.com/demo/sneat-bootstrap-html-admin-template/documentation" target="_blank" class="footer-link me-4">Documentation</a>
                                        <a href="https://themeselection.com/support" target="_blank" class="footer-link me-4">Support</a>
                                    </div>
                                </div>
                            </footer>*@
                        <!-- / Footer -->

                        <div class="content-backdrop fade"></div>
                    
                    <!-- Content wrapper -->
                
                <!-- / Layout page -->
            

            <!-- Overlay -->
            <div class="layout-overlay layout-menu-toggle"></div>
        
        

WorkHub/Views/Developer/DeploymentStatus.cshtml
@{
    ViewBag.Title = "DeploymentStatus";
    Layout = "~/Views/Developer/DeveloperIndex.cshtml";
}

<div class="container">
    <div class="row mt-5">
        <div class="col">
            <h1>Deployment Status Page</h1>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col">
            <!-- Deployment status cards -->
            <div class="card deployment">
                <div class="card-body">
                    <h5 class="card-title">Production Environment</h5>
                    <p class="card-text">Status: Live</span></p>
                    <p class="card-text">Deployed: June 15, 2024 10:00 AM</p>
                    <p class="card-text">Version: v1.0.0</p>
                    <a href="#" class="btn btn-sm btn-primary">View Details</a>
                </div>
            </div>

            <div class="card deployment">
                <div class="card-body">
                    <h5 class="card-title">Staging Environment</h5>
                    <p class="card-text">Status: Testing</span></p>
                    <p class="card-text">Deployed: June 16, 2024 11:00 AM</p>
                    <p class="card-text">Version: v1.1.0-beta</p>
                    <a href="#" class="btn btn-sm btn-primary">View Details</a>
                </div>
            </div>

            <div class="card deployment">
                <div class="card-body">
                    <h5 class="card-title">Development Environment</h5>
                    <p class="card-text">Status: Inactive</span></p>
                    <p class="card-text">Deployed: Not deployed yet</p>
                    <p class="card-text">Version: N/A</p>
                    <a href="#" class="btn btn-sm btn-primary">View Details</a>
                </div>
            </div>

            <!-- Add more deployment status cards as needed -->
        </div>
    </div>
</div>

WorkHub/Views/Developer/LogIn.cshtml
@{
    ViewBag.Title = "LogIn";
}

<body>

</body>

WorkHub/Views/Developer/NewBuild.cshtml
@{
    ViewBag.Title = "NewBuild";
    Layout = "~/Views/Developer/DeveloperIndex.cshtml";
}

<div class="container mt-5">
    <h1 class="mb-4">Trigger New Build</h1>

    <form id="buildForm">
        <div class="form-group">
            <label for="branchName">Branch Name</label>
            <input type="text" class="form-control" id="branchName" placeholder="Enter branch name" required>
        </div>

        <div class="form-group">
            <label for="buildOptions">Build Options</label>
            <select class="form-control" id="buildOptions">
                <option>Debug</option>
                <option>Release</option>
            </select>
        </div>

        <div class="form-group">
            <label for="commitMessage">Commit Message</label>
            <input type="text" class="form-control" id="commitMessage" placeholder="Enter commit message">
        </div>

        <button type="submit" class="btn btn-primary">Trigger Build</button>
    </form>

    <div id="buildStatus" class="mt-4">
        <!-- Build status will be displayed here -->
    </div>
</div>