WorkHub/Models/Kanban Models/Kanban.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WorkHub.Models
{
    public class Kanban
    {
        public List<KanbanColumn> KanbanColumns { get; set; }
    }
}

WorkHub/Controllers/KanbanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;
using WorkHub.Models;
using WorkHub.Services;

namespace WorkHub.Controllers
{
    public class KanbanController : Controller
    {
        private readonly IMongoCollection<Tasks> _tasksCollection;
        private readonly IMongoCollection<CreateaProject> _projectsCollection;
        private readonly IMongoCollection<File> _taskFileCollection;
        private readonly IMongoCollection<Task> _taskCollection;
        private readonly IMongoCollection<TaskCompletionRequest> _taskCompletionRequestCollection;
        public readonly IMongoCollection<Comment> _commentCollection;

        public KanbanController()
        {
            _tasksCollection = MongoDBHelper.GetCollection<Tasks>("Tasks");
            _projectsCollection = MongoDBHelper.GetCollection<CreateaProject>("Project");
            _taskFileCollection = MongoDBHelper.GetCollection<File>("TaskFiles");
            _taskCollection = MongoDBHelper.GetCollection<Task>("Tasks");
            _taskCompletionRequestCollection = MongoDBHelper.GetCollection<TaskCompletionRequest>("TaskCompletionRequest");
            _commentCollection = MongoDBHelper.GetCollection<Comment>("Comment");
        }

        public ActionResult Index(string id)
        {
            List<CreateaProject> projects = _projectsCollection.Find(_ => true).ToList();
            ViewBag.Projects = projects;

            CreateaProject selectedProject = null;
            if (string.IsNullOrEmpty(id))
            {
                selectedProject = projects.FirstOrDefault();
            }
            else
            {
                selectedProject = projects.FirstOrDefault(p => p.Id == id);
            }

            Dictionary<string, long> taskFileCounts = new Dictionary<string, long>();
            Dictionary<string, long> taskCommentCounts = new Dictionary<string, long>();

            if (selectedProject != null)
            {
                ViewBag.SelectedProject = selectedProject;
                var KanbanColumns = new List<KanbanColumn>
                {
                    new KanbanColumn { Title = "To Do", Cards = GetCardsByColumnStat("To Do", selectedProject.Id) },
                    new KanbanColumn { Title = "In Progress", Cards = GetCardsByColumnStat("In Progress", selectedProject.Id) },
                    new KanbanColumn { Title = "Done", Cards = GetCardsByColumnStat("Done", selectedProject.Id) }
                };

                ;
                var projectTasks = _tasksCollection.Find(t => t.ProjectID == selectedProject.Id).ToList();

                foreach (var task in projectTasks)
                {
                    var fileCount = _taskFileCollection.CountDocuments(tf => tf.TaskID == task.Id);
                    var commentCount = _commentCollection.CountDocuments(c => c.RelatedId == task.Id);
                    taskFileCounts[task.Id] = fileCount;
                    taskCommentCounts[task.Id] = commentCount;
                }

                ViewBag.TaskFileCounts = taskFileCounts;
                ViewBag.TaskCommentCounts = taskCommentCounts;

                return View(KanbanColumns);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult DeleteTask(string taskId, string projectId)
        {
            try
            {
                DeleteFiles(taskId);

                var filter = Builders<Tasks>.Filter.Eq(card => card.Id, taskId);
                _tasksCollection.DeleteOne(filter);

                var filter2 = Builders<TaskCompletionRequest>.Filter.Eq(tr => tr.TaskId, taskId);
                _taskCompletionRequestCollection.DeleteMany(filter2);

                return RedirectToAction("Index", new { id = projectId });
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Error deleting task: " + ex.Message;
                return View("Index");
            }
        }


        private void DeleteFiles(string taskid)
        {
            var database = MongoDBHelper.GetDatabase();
            
            var taskFilesCollection = MongoDBHelper.GetCollection<Models.File>("TaskFiles");

            
            var taskFilesToDelete = taskFilesCollection.Find(tf => tf.TaskID == taskid).ToList();

            foreach (var taskFile in taskFilesToDelete)
            {
                
                var filePath = taskFile.FilePath;

                
                var filesCollection = database.GetCollection<BsonDocument>("fs.files");
                var fileDocument = filesCollection.Find(Builders<BsonDocument>.Filter.Eq("filename", filePath)).FirstOrDefault();

                if (fileDocument != null)
                {
                    var fileId = fileDocument["_id"].AsObjectId;

                    
                    var chunksCollection = database.GetCollection<BsonDocument>("fs.chunks");
                    chunksCollection.DeleteMany(Builders<BsonDocument>.Filter.Eq("files_id", fileId));

                    
                    filesCollection.DeleteMany(Builders<BsonDocument>.Filter.Eq("_id", fileId));
                }
            }

            
            var filter = Builders<Models.File>.Filter.In(f => f.Id, taskFilesToDelete.Select(tf => tf.Id));
            taskFilesCollection.DeleteMany(filter);
        }


        [HttpPost]
        public ActionResult UpdateCard(string id, string newStatus, string selectedProject)
        {
            try
            {
                var filter = Builders<Tasks>.Filter.Eq(card => card.Id, id);
                var update = Builders<Tasks>.Update.Set(card => card.Status, newStatus);

                _tasksCollection.UpdateOne(filter, update);

                return RedirectToAction("Index", new { id = ViewBag.SelectedProject.Id });
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Error updating task: " + ex.Message;
                return RedirectToAction("Index", new { id = selectedProject });
            }
        }

        private List<Tasks> GetCardsByColumnStat(string status, string projectId)
        {
            var filter = Builders<Tasks>.Filter.And(
                Builders<Tasks>.Filter.Eq(card => card.Status, status),
                Builders<Tasks>.Filter.Eq(card => card.ProjectID, projectId)
            );
            return _tasksCollection.Find(filter).ToList();
        }
    }
}

WorkHub/Controllers/TaskController.cs
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WorkHub.Models;
using WorkHub.Services;
using System.IO;
using MongoDB.Driver.GridFS;
using System.Threading.Tasks;
using System.Security.Cryptography.X509Certificates;

namespace WorkHub.Controllers
{
    public class TaskController : Controller
    {

        public readonly IMongoCollection<Tasks> _tasksCollection;
        public readonly IMongoCollection<CreateaProject> _projectsCollection;
        public readonly IMongoCollection<UserSignUp> _userCollection;
        public readonly IMongoCollection<Models.File> _taskFileCollection;
        public readonly IMongoCollection<TaskCompletionRequest> _taskCompletionRequestCollection;
        public readonly IMongoCollection<Comment> _commentCollection;
        public readonly IMongoCollection<UserProfile> _userProfilesCollection;
        public readonly IMongoCollection<Notification> _userNotificationsCollection;

        public TaskController()
        {
            _tasksCollection = MongoDBHelper.GetCollection<Tasks>("Tasks");
            _projectsCollection = MongoDBHelper.GetCollection<CreateaProject>("Project");
            _userCollection = MongoDBHelper.GetCollection<UserSignUp>("Users");
            _taskFileCollection = MongoDBHelper.GetCollection<Models.File>("TaskFile");
            _taskCompletionRequestCollection = MongoDBHelper.GetCollection<TaskCompletionRequest>("TaskCompletionRequest");
            _commentCollection = MongoDBHelper.GetCollection<Comment>("Comment");
            _userProfilesCollection = MongoDBHelper.GetCollection<UserProfile>("UserProfiles");
            _userNotificationsCollection = MongoDBHelper.GetCollection<Notification>("Notifications");
        }

        public ActionResult TasksList()
        {
            try
            {
                var projects = _projectsCollection.Find(_ => true).ToList();

                ViewBag.Projects = projects;

                var tasks = _tasksCollection.Find(_ => true).ToList();
                var projectNames = new List<string>();

                for (int i = 0; i < tasks.Count; i++)
                {
                    var project = _projectsCollection.Find(p => p.Id == tasks[i].ProjectID).FirstOrDefault();
                    if (project != null)
                    {
                        projectNames.Add(project.ProjectName);
                    }
                    else
                    {
                        projectNames.Add(" ");
                    }
                }

                ViewBag.ProjectNames = projectNames;
                return View(tasks);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while fetching tasks.");
                return View(new List<Tasks>());
            }
        }

        public ActionResult TaskDetails(string id)
        {
            try
            {

                var task = _tasksCollection.Find(t => t.Id == id).FirstOrDefault();
                if (task == null)
                {
                    return HttpNotFound();
                }

                var users = new Dictionary<string, string>();

                if (task.Assignee != null)
                {
                    for (int i = 0; i < task.Assignee.Count; i++)
                    {
                        var user = _userCollection.Find(u => u.Id == task.Assignee[i]).FirstOrDefault();
                        if (user != null)
                        {
                            users.Add(user.Username, user.Role);
                        }
                    }
                }

                var project = _projectsCollection.Find(p => p.Id == task.ProjectID).FirstOrDefault();
                ViewBag.ProjectName = project.ProjectName;


                var teamMembers = project.TeamMembers;
                foreach (var user in teamMembers)
                {
                    UserSignUp memberinfo = _userCollection.Find(u => u.Id == user).FirstOrDefault();

                    if (memberinfo.Role == "manager")
                    {
                        ViewBag.ManagerId = memberinfo.Id;
                    }
                }

                ViewBag.Users = users;

                ObjectId taskObjectId;
                if (!ObjectId.TryParse(id, out taskObjectId))
                {
                    return HttpNotFound();
                }


                var taskFilesCollection = MongoDBHelper.GetCollection<Models.File>("TaskFiles");


                var taskFiles = taskFilesCollection.Find(file => file.TaskID == id).ToList();


                if (taskFiles == null || taskFiles.Count == 0)
                {

                    ViewBag.TaskFiles = new List<Models.File>();
                }
                else
                {
                    ViewBag.TaskFiles = taskFiles;
                }

                var comments = _commentCollection.Find(c => c.RelatedId == id).ToList();

                Dictionary<string, string> commentUserPictures = new Dictionary<string, string>();
                foreach (var comment in comments)
                {
                    var user = _userProfilesCollection.Find(u => u.Id == comment.UserId).FirstOrDefault();
                    if (user != null)
                    {
                        commentUserPictures.Add(comment.Id, user.ProfilePicture);
                    }
                }

                ViewBag.CommentUserPictures = commentUserPictures;
                ViewBag.MyID = Request.Cookies["UserID"].Value.ToString();
                ViewBag.MyName = Request.Cookies["UserName"].Value.ToString();


                return View((task, taskFiles, comments));
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "An error occurred while fetching project details.");



                return View(new CreateaProject());
            }
        }

        public ActionResult DownloadFile(string fileId)
        {
            try
            {
                var objectId = new ObjectId(fileId);

                var taskFilesCollection = MongoDBHelper.GetCollection<Models.File>("TaskFiles");
                var taskFile = taskFilesCollection.Find(f => f.Id == objectId).FirstOrDefault();

                if (taskFile == null)
                {
                    return HttpNotFound("File not found.");
                }

                var database = MongoDBHelper.GetDatabase();
                var bucket = new GridFSBucket(database);

                byte[] fileBytes;
                using (var stream = new MemoryStream())
                {
                    bucket.DownloadToStreamByName(taskFile.FilePath, stream);
                    fileBytes = stream.ToArray();
                }

                return File(fileBytes, taskFile.ContentType, taskFile.FileName);
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Error downloading file: " + ex.Message;
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult DeleteFiles(string taskid, string[] fileIds)
        {
            if (fileIds != null && fileIds.Length > 0)
            {
                var database = MongoDBHelper.GetDatabase();

                var taskFilesCollection = MongoDBHelper.GetCollection<Models.File>("TaskFiles");
                var taskFilesToDelete = taskFilesCollection.Find(f => fileIds.Contains(f.Id.ToString())).ToList();

                foreach (var taskFile in taskFilesToDelete)
                {
                    var filePath = taskFile.FilePath;

                    var filesCollection = database.GetCollection<BsonDocument>("fs.files");
                    var fileDocument = filesCollection.Find(Builders<BsonDocument>.Filter.Eq("filename", filePath)).FirstOrDefault();

                    if (fileDocument != null)
                    {
                        var fileId = fileDocument["_id"].AsObjectId;

                        var chunksCollection = database.GetCollection<BsonDocument>("fs.chunks");
                        chunksCollection.DeleteMany(Builders<BsonDocument>.Filter.Eq("files_id", fileId));

                        filesCollection.DeleteMany(Builders<BsonDocument>.Filter.Eq("_id", fileId));
                    }
                }

                var filter = Builders<Models.File>.Filter.In(f => f.Id, taskFilesToDelete.Select(tf => tf.Id));
                taskFilesCollection.DeleteMany(filter);
            }

            return RedirectToAction("TaskDetails", new { id = taskid });
        }

        public ActionResult AddTask(int act, string id, string projectID, string title, string desc, string repID, string repName, string dueDate, string AssignDate, string estTime, string status)
        {
            try
            {
                if (act == 1)
                {

                    var projects = _projectsCollection.Find(_ => true).ToList();


                    ViewBag.Projects = projects;
                    ViewBag.Name = Request.Cookies["UserName"].Value.ToString();
                    ViewBag.ID = Request.Cookies["UserID"].Value.ToString();
                    ViewBag.act = 1;


                    var users = _userCollection.Find(_ => true).ToList();


                    ViewBag.Users = users;


                    return View();
                }
                else if (act == 2)
                {

                    var projects = _projectsCollection.Find(_ => true).ToList();
                    Tasks model = _tasksCollection.Find(t => t.Id == id).FirstOrDefault();


                    ViewBag.Projects = projects;
                    ViewBag.Name = Request.Cookies["UserName"].Value.ToString();

WorkHub/Views/Kanban/Index.cshtml
@model List<WorkHub.Models.KanbanColumn>
@{
    ViewBag.Title = "Kanban Board";
    Layout = "~/Views/Manager/ManagerIndex.cshtml";
    var role = Request.Cookies["UserRole"].Value;
}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12">
            <h1 class="text-center my-4">Kanban Board</h1>
            <div class="mb-4">
                <form id="projectForm" method="get" action="@Url.Action("Index", "Kanban")">
                    <label for="projectSelect" class="form-label">Select Project</label>
                    <select id="projectSelect" name="id" class="form-select" onchange="document.getElementById('projectForm').submit();">
                        @foreach (var project in ViewBag.Projects)
                        {
                            <option value="@project.Id" @(ViewBag.SelectedProject != null && ViewBag.SelectedProject.Id == project.Id ? "selected" : "")>@project.ProjectName</option>
                        }
                    </select>
                </form>
            </div>
            <div class="kanban-board d-flex justify-content-center flex-wrap">
                @for (int i = 0; i < Model.Count; i++)
                {
                    var column = Model[i];
                    <div class="kanban-column mb-4 shadow border rounded">
                        <h5 class="kanban-title text-center">@column.Title</h5>
                        @foreach (var card in column.Cards)
                        {
                            <a class="h5" href="@Url.Action("TaskDetails", "Task", new { id = card.Id })" style="text-decoration:none;">
                                <div class="kanban-card mb-3 border rounded">
                                    <div class="kanban-card-header d-flex justify-content-between align-items-center p-2">
                                        <span class="text-primary fw-bold">@card.TaskTitle</span>
                                        <div class="dropdown">
                                            @if (role != "developer")
                                            {<button class="btn p-0" type="button" id="cardOpt1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="bx bx-dots-vertical-rounded"></i>
                                                </button>}
                                            <div class="dropdown-menu" aria-labelledby="cardOpt1">
                                                @if (card.Status != "To Do")
                                                {
                                                    <form action="@Url.Action("UpdateCard", "Kanban")" method="post" class="d-inline">
                                                        <input type="hidden" name="id" value="@card.Id" />
                                                        <input type="hidden" name="newStatus" value="To Do" />
                                                        <input type="hidden" name="selectedProject" value="@ViewBag.SelectedProject.Id" />
                                                        <button type="submit" class="dropdown-item">Send to To Do</button>
                                                    </form>
                                                }
                                                @if (card.Status != "In Progress")
                                                {
                                                    <form action="@Url.Action("UpdateCard", "Kanban")" method="post" class="d-inline">
                                                        <input type="hidden" name="id" value="@card.Id" />
                                                        <input type="hidden" name="newStatus" value="In Progress" />
                                                        <input type="hidden" name="selectedProject" value="@ViewBag.SelectedProject.Id" />
                                                        <button type="submit" class="dropdown-item">Send to In Progress</button>
                                                    </form>
                                                }
                                                @if (card.Status != "Done")
                                                {
                                                    <form action="@Url.Action("UpdateCard", "Kanban")" method="post" class="d-inline">
                                                        <input type="hidden" name="id" value="@card.Id" />
                                                        <input type="hidden" name="newStatus" value="Done" />
                                                        <input type="hidden" name="selectedProject" value="@ViewBag.SelectedProject.Id" />
                                                        <button type="submit" class="dropdown-item">Send to Done</button>
                                                    </form>
                                                }
                                                <div class="dropdown-divider" bis_skin_checked="1"></div>
                                                <form action="@Url.Action("DeleteTask", "Kanban")" method="post" class="d-inline">
                                                    <input type="hidden" name="taskId" value="@card.Id" />
                                                    <input type="hidden" name="ProjectId" value="@ViewBag.SelectedProject.Id" />
                                                    <button type="submit" class="dropdown-item text-danger">Delete Task</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="kanban-card-body p-2">
                                        <p class="mb-1">@card.Description</p>
                                        <div class="kanban-card-footer d-flex justify-content-between align-items-center mt-2">
                                            <div><i class="bi bi-chat"></i> @ViewBag.TaskCommentCounts[card.Id] <i class="bi bi-paperclip"></i> @ViewBag.TaskFileCounts[card.Id]</div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        }

                        <form action="@Url.Action("CreateFromKanban", "Task", new { ProjectId = ViewBag.SelectedProject.Id })" method="post" class="d-inline">
                            <input type="hidden" name="ColumnNo" value="@i" />
                            <input type="hidden" name="ProjectId" value="@ViewBag.SelectedProject.Id" />
                            <button type="button" class="kanban-add-item btn btn-outline-primary w-100" data-toggle="modal" data-target="#exampleModal-@i">+ Add New Item</button>
                            <div class="modal fade" id="exampleModal-@i" tabindex="-1" aria-labelledby="exampleModalLabel-@i" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel-@i">New Task</h5>
                                            <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="mb-3">
                                                <label for="exampleFormControlInput1-@i" class="form-label">Task Title</label>
                                                <input type="text" name="Header" class="form-control" id="exampleFormControlInput1-@i" required>
                                            </div>
                                            <div class="mb-3">
                                                <label for="exampleFormControlTextarea1-@i" class="form-label">Description</label>
                                                <textarea name="Body" class="form-control" id="exampleFormControlTextarea1-@i" rows="3" required></textarea>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Add Task</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">

<style>
    .kanban-board {
        gap: 20px;
        overflow-x: auto;
        display: flex;
        justify-content: center;
    }

    .kanban-column {
        background: #f8f9fa;
        border-radius: 8px;
        padding: 15px;
        width: 350px;
        flex-shrink: 0;
        border: 1px solid #dee2e6;
    }

    .kanban-title {
        font-weight: bold;
        margin-bottom: 15px;
        color: #343a40;
    }

    .kanban-card {
        background: #ffffff;
        border-radius: 8px;
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
        margin-bottom: 10px;
        padding: 10px;
        transition: box-shadow 0.3s ease;
    }

        .kanban-card:hover {
            box-shadow: 0 6px 12px rgba(0, 0, 0, 0.1);
        }

    .kanban-card-header {
        font-size: 0.9rem;
        font-weight: bold;
        margin-bottom: 5px;
        color: #6c757d;
    }

    .kanban-card-body p {
        margin-bottom: 10px;
        font-size: 0.85rem;
    }

    .kanban-card-footer {
        font-size: 0.75rem;
        color: #6c757d;
    }

    .kanban-add-item {
        border-radius: 8px;
        padding: 10px;
        text-align: center;
        cursor: pointer;
        font-size: 0.85rem;
        color: #007bff;
        transition: background-color 0.2s;
    }

        .kanban-add-item:hover {
            background: #e2e6ea;
        }

    .delete-icon {
        color: gray;
        transition: color 0.3s;
    }

        .delete-icon:hover {
            color: red;
        }
</style>